export default [
  {
    path: '/',
    redirect: '/dashboard',
  },
  {
    path: '/login',
    layout: false,
    component: './Login',
  },
  {
    name: '智造总览',
    icon: 'DashboardOutlined',
    path: '/dashboard',
    component: './Dashboard',
    access: 'authenticated',
  },
  {
    name: '订单履约',
    icon: 'FileDoneOutlined',
    path: '/orders',
    access: 'authenticated',
    routes: [
      { name: '销售订单', path: '/orders/sales', component: './Placeholder' },
      { name: '交付预测', path: '/orders/forecast', component: './Placeholder' },
      { name: '风险订单', path: '/orders/at-risk', component: './Placeholder' },
    ],
  },
  {
    name: '生产运营',
    icon: 'ControlOutlined',
    path: '/operations',
    access: 'authenticated',
    routes: [
      { name: '生产计划', path: '/operations/planning', component: './Placeholder' },
      { name: 'APS 排程', path: '/operations/aps', component: './Placeholder' },
      { name: '生产工单', path: '/operations/work-orders', component: './Placeholder' },
      { name: '生产执行', path: '/operations/execution', component: './Placeholder' },
      { name: '产能分析', path: '/operations/capacity', component: './Placeholder' },
    ],
  },
  {
    name: '物料与库存',
    icon: 'AppstoreOutlined',
    path: '/materials',
    access: 'authenticated',
    routes: [
      { name: '物料齐套', path: '/materials/readiness', component: './Placeholder' },
      { name: '缺料分析', path: '/materials/shortage', component: './Placeholder' },
      { name: '库存管理', path: '/materials/inventory', component: './Placeholder' },
      { name: '批次库存', path: '/materials/lots', component: './Placeholder' },
      { name: '库存预留', path: '/materials/reservations', component: './Placeholder' },
    ],
  },
  {
    name: '采购与供应',
    icon: 'TruckOutlined',
    path: '/supply',
    access: 'authenticated',
    routes: [
      { name: '采购订单', path: '/supply/purchase-orders', component: './Placeholder' },
      { name: '供应商', path: '/supply/suppliers', component: './Placeholder' },
      { name: '供应风险', path: '/supply/risks', component: './Placeholder' },
      { name: '到货管理', path: '/supply/receipts', component: './Placeholder' },
    ],
  },
  {
    name: '质量管理',
    icon: 'SafetyCertificateOutlined',
    path: '/quality',
    access: 'authenticated',
    routes: [
      { name: '质量异常', path: '/quality/issues', component: './Placeholder' },
      { name: 'Quality Hold', path: '/quality/holds', component: './Placeholder' },
      { name: '检验批次', path: '/quality/inspections', component: './Placeholder' },
      { name: 'NCR', path: '/quality/ncr', component: './Placeholder' },
    ],
  },
  {
    name: '异常管理',
    icon: 'WarningOutlined',
    path: '/exceptions',
    access: 'authenticated',
    routes: [
      { name: '异常中心', path: '/exceptions/center', component: './Placeholder' },
      { name: '风险预警', path: '/exceptions/alerts', component: './Placeholder' },
      { name: '事件时间线', path: '/exceptions/timeline', component: './Placeholder' },
    ],
  },
  {
    name: 'AI 智能决策',
    icon: 'RobotOutlined',
    path: '/ai',
    access: 'authenticated',
    routes: [
      { name: 'Decision Center', path: '/ai/decisions', component: './Placeholder' },
      { name: 'What-if 推演', path: '/ai/what-if', component: './Placeholder' },
      { name: 'Agent Workspace', path: '/ai/workspace', component: './Placeholder' },
      { name: 'Agent Trace', path: '/ai/agent-trace', component: './Placeholder' },
      { name: '决策历史', path: '/ai/history', component: './Placeholder' },
    ],
  },
  {
    name: '审批中心',
    icon: 'AuditOutlined',
    path: '/approvals',
    access: 'authenticated',
    routes: [
      { name: '待我审批', path: '/approvals/pending', component: './Placeholder' },
      { name: '我的申请', path: '/approvals/mine', component: './Placeholder' },
      { name: '审批记录', path: '/approvals/history', component: './Placeholder' },
    ],
  },
  {
    name: '基础数据',
    icon: 'DatabaseOutlined',
    path: '/master-data',
    access: 'authenticated',
    routes: [
      { name: '工厂与产线', path: '/master-data/plants', component: './Placeholder' },
      { name: '设备与工作中心', path: '/master-data/resources', component: './Placeholder' },
      { name: '物料', path: '/master-data/materials', component: './Placeholder' },
      { name: 'BOM', path: '/master-data/boms', component: './Placeholder' },
      { name: 'Routing', path: '/master-data/routings', component: './Placeholder' },
      { name: '供应商主数据', path: '/master-data/suppliers', component: './Placeholder' },
    ],
  },
  {
    name: '系统管理',
    icon: 'SettingOutlined',
    path: '/system',
    access: 'authenticated',
    routes: [
      {
        name: '服务状态',
        path: '/system/health',
        component: './SystemHealth',
        access: 'authenticated',
      },
      {
        name: '组织架构',
        path: '/system/organization',
        component: './SystemOrganization',
        access: 'canReadEnterprise',
      },
      {
        name: '用户管理',
        path: '/system/users',
        component: './SystemUsers',
        access: 'canReadUsers',
      },
      {
        name: '角色与权限',
        path: '/system/rbac',
        component: './SystemRoles',
        access: 'canReadRbac',
      },
      {
        name: '数据权限',
        path: '/system/data-scope',
        component: './SystemDataScope',
        access: 'canReadDataScope',
      },
      {
        name: '集成中心',
        path: '/system/integrations',
        component: './Placeholder',
        access: 'authenticated',
      },
      {
        name: '审计日志',
        path: '/system/audit',
        component: './Placeholder',
        access: 'canReadAudit',
      },
    ],
  },
  {
    path: '*',
    layout: false,
    component: './NotFound',
  },
];
